project_id = "ytgmzhevgcmvevuwkocz"

[functions.send-contact-email]
verify_jwt = false

[functions.blog-formatter]
verify_jwt = false

[functions.publish-scheduled-posts]
verify_jwt = false
schedule = "0 * * * *"
